version: "3.9"

services:
  control-plane:
    image: registry.synadia.io/control-plane:1.4.2-rc.0
    command: ["server", "start"]
    volumes:
      - ./syn-cp.yaml:/app/syn-cp.yaml
      - cp-data:/app/data
    ports:
      - 8080:8080
      - 8443:8443

  nats1:
    image: nats:alpine
    ports:
      - 4222:4222
      - 8222:8222
    volumes:
      - ./nats1.conf:/etc/nats/nats-server.conf
      - ./shared.conf:/etc/nats/shared.conf
      - nats1-data:/data

  nats2:
    image: nats:alpine
    ports:
      - 4223:4222
      - 8223:8222
    volumes:
      - ./nats2.conf:/etc/nats/nats-server.conf
      - ./shared.conf:/etc/nats/shared.conf
      - nats2-data:/data

  nats3:
    image: nats:alpine
    ports:
      - 4224:4222
      - 8224:8222
    volumes:
      - ./nats3.conf:/etc/nats/nats-server.conf
      - ./shared.conf:/etc/nats/shared.conf
      - nats3-data:/data

volumes:
  cp-data: {}
  nats1-data: {}
  nats2-data: {}
  nats3-data: {}
