services:
  control-plane:
    image: registry.synadia.io/control-plane:1.4.2
    command: ["server", "start"]
    volumes:
      - ./syn-cp.yaml:/app/syn-cp.yaml
      - cp-data:/app/data
    ports:
      - 8080:8080

  nats1:
    image: docker.io/nats:alpine
    ports:
      - 4222:4222
      - 8222:8222
    volumes:
      - ./nats1.conf:/etc/nats/nats-server.conf
      - ./shared.conf:/etc/nats/shared.conf
      - nats1-data:/data

  nats2:
    image: docker.io/nats:alpine
    ports:
      - 4223:4222
      - 8223:8222
    volumes:
      - ./nats2.conf:/etc/nats/nats-server.conf
      - ./shared.conf:/etc/nats/shared.conf
      - nats2-data:/data

  nats3:
    image: docker.io/nats:alpine
    ports:
      - 4224:4222
      - 8224:8222
    volumes:
      - ./nats3.conf:/etc/nats/nats-server.conf
      - ./shared.conf:/etc/nats/shared.conf
      - nats3-data:/data

  http-gateway:
    image: registry.synadia.io/http-gateway:latest
    environment:
      NHG_PORT: "8081"
      NHG_URL: "nats://nats1:4222,nats://nats2:4222,nats://nats3:4222"
      NHG_TOKENS_BUCKET: "tokens"
      NHG_PROVIDER_CREDS: "/http-gateway.creds"
      NHG_DISABLE_LOGGING: "false"
    ports:
      - 8081:8081
    command:
      - "run"
    volumes:
      - ./http-gateway.creds:/http-gateway.creds

volumes:
  cp-data: {}
  nats1-data: {}
  nats2-data: {}
  nats3-data: {}
