name: Test Scripts

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test Scripts
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Test Scripts
        env:
          SYNADIA_CR_USERNAME: ${{ secrets.SYNADIA_CR_USERNAME }}
          SYNADIA_CR_PASSWORD: ${{ secrets.SYNADIA_CR_PASSWORD }}
        shell: bash
        run: |
          curl -fsSL https://raw.githubusercontent.com/synadia-io/platform-trial/refs/heads/main/scripts/bootstrap.sh | bash -s
          cd ./platform-trial
          ./scripts/test.sh
          ./scripts/stop.sh
      
      - name: Debug
        if: failure()
        run: |
          cd ./platform-trial
          cat .env
          cat shared.conf
          cat trial.creds
          cat http-gateway.creds
