name: Test Scripts

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test Scripts
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Test bootstraph.sh
        run: |
          sh <(curl --location https://raw.githubusercontent.com/synadia-io/platform-trial/refs/heads/update-trial/scripts/bootstrap.sh)
